### ISSUE TITLE
Question - Any solution to Resume Parse docx file?

### ISSUE THREAD

**Issue by pdns90** [edenai/edenai-apis#105]
Hi there, I am trying to upload docx file but getting not supported docx file type in resume parse api.

Could you please let me know if any provider that's support docx?

Thanks,

**Comment by DninoAdnane** [comment]
Hello @pdns90,
For resume parser, their is `Senseloaf` that supports DOCx files. However, using the Edenai API, you can pass the parameter `convert_to_pdf` to *true, which will convert the file for you to pdf before parsing it
