### ISSUE TITLE
I'm trying to use generic OCR sending a 3 page pdf and EDEN is not working extracting text

### ISSUE THREAD

**Issue by marcosmarf27** [edenai/edenai-apis#28]
I'm trying to use generic OCR sending a 3 page pdf and EDEN is not working extracting text,  it works just sending images, I need to send pdf and extract text.

**Comment by SamyMe** [comment]
Hi, You do need to convert your pdf to a list of images and send them one by one.
We're working on releasing a new async OCR features that can handle multiple pages OCR.
